name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10'

    - name: Install nswag
      run: npm install nswag@14.0.3 -g

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Install client dependencies
      run: cd client && npm install

    - name: Build api
      run:
        nswag run apigen.nswag
        
    - name: Build clirnt
      run:
        nswag run clientgen.nswag

    - name: Run application
      run: 
        dotnet run --project server -lp https
