name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Linux для совместимости с .NET Core SDK

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Укажите версию Node.js, совместимую с вашим проектом

    - name: Install nswag
      run: npm install nswag@14.0.3 -g

    - name: Restore NuGet packages and build project
      run: |
        dotnet restore
        cd client
        npm install
        cd ..
        dotnet build

    - name: Generate API code
      run: |
        dotnet nswag run apigen.nswag
        dotnet nswag run clientgen.nswag

    - name: Run application
      run: dotnet run --project server -lp https
